# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87dc9fe3ef1fd16d6071f60e3fb7d1057fa09bd484210d4cfe3367a3aa4f7029ab42b43793577d06910e8a134fa499b3816f6a4a7f1ce79cdb269d41e0591954

test:
  secret_key_base: 66068157c4d4253fb32e58f388fde6ec8ce17b4100b9976b4e2b191fa4e5fbbf2f30ca848df3945ddb9c01067af9ea7e4ebbada50096315353e886dfe13a2c65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
